live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = false
size = 15.0
# use_thin_strokes = false

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[shell]
args = ["-l", "-c", "tmux attach -t main || tmux new-session -s main"]
program = "/bin/zsh"

[window]
blur = false
decorations = "None"
dynamic_padding = true
opacity = 0.9

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
